[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcd = "2.3.0"
regex = "1.5"
memoize = "0.4.1"
nalgebra = "0.32.3"
itertools = "0.10.0"
pathfinding = "4.6.0"
